/* 
(서울) 0. 서울 전수 + 2019년
(전국) 1. 2003년, 2010년, 2019년 1% 가구(서울 포함 전국) 추출 + 가구원 + 가족 
(전국) 2. 2010년 1% 가구 표본의 2003-2019년 가구와 가구원 정보 */

/* (서울) 0. 서울 전수 + 2019년 */
PROC SQL;DROP TABLE SAPTMP.TMP_INDI_&P_N._ALL;
connect to saphana as x1(server=pepper1 port=30015 user=&DB_USER password=!&DB_USER1 readbuff=32767 insertbuff=32767);
execute
(
	CREATE TABLE TMP_INDI_&P_N._ALL AS 
	( 
		SELECT DISTINCT INDI_DSCM_NO
		FROM NHISBDA.HHDT_DSES_YY
			WHERE STD_YYYY BETWEEN '2002' AND '2019'
			AND STD_YYYY >= BYEAR
			AND SUBSTR(RVSN_ADDR_CD,1,2) = '11'
	)
) by x1;
disconnect from x1;
QUIT;  
PROC SQL;SELECT COUNT(DISTINCT INDI_DSCM_NO) FROM SAPTMP.TMP_INDI_&P_N._ALL;QUIT;

/* (전국) 가구주 */
PROC SQL;
connect to saphana as x1(server=pepper1 port=30015 user=&DB_USER password=!&DB_USER1 readbuff=32767 insertbuff=32767);
DROP TABLE SAPTMP.TMP_C20_0519;
CREATE TABLE SAPTMP.TMP_C20_0519 AS 
SELECT * 
FROM CONNECTION TO X1
	(SELECT STD_YYYY, DISTINCT(HHRR_HEAD_INDI_DSCM_NO)
	FROM NHISBDA.HHDT_DSES_YY 
	WHERE STD_YYYY IN ('2003', '2010', '2019') /* 2003, 2010, 2019년만, 서울 포함 전국 */
	ORDER BY 1
	);disconnect from x1;
QUIT;


/* (전국) 1.	2003년, 2010년, 2019년 1% 가구(서울 포함 전국) 추출 + 가구원 + 가족 
		 1.1	3개년마다 가구 중 1% 랜덤 샘플링 */
PROC SURVEYSELECT DATA=SAPTMP.TMP_C20_0519 METHOD=SRS SEED=170011 RATE=0.01 OUT=AA.TG_SMPL_XSECTION_HEAD ;STRATA STD_YYYY; RUN;
PROC SQL;DROP TABLE SAPTMP.TMP_INDI_&P_N._SMPL_XSECTION;QUIT;
DATA SAPTMP.TMP_INDI_&P_N._SMPL_XSECTION;SET AA.TG_SMPL_XSECTION_HEAD; KEEP HHRR_HEAD_INDI_DSCM_NO STD_YYYY;RUN; /*기존 코드에서 AA.TG_SMPL이 어떻게 생성되었는지 모르겠어서 우선 위 SURVEYSELECT 아웃풋으로 set 했습니다.*/


/* (전국) 2.		2010년 1% 가구 표본의 2003-2019년 가구와 가구원 정보
		 2.1	2010년 가구중 1% 랜덤 샘플링 */
PROC SURVEYSELECT DATA=SAPTMP.TMP_C20_0519 (WHERE = (STD_YYYY='2010')) METHOD=SRS SEED=170011 RATE=0.01 OUT=AA.TG_SMPL_PANEL_HEAD ;STRATA STD_YYYY; RUN;
PROC SQL;DROP TABLE SAPTMP.TMP_INDI_&P_N._SMPL_PANEL;QUIT;
DATA SAPTMP.TMP_INDI_&P_N._SMPL_PANEL;SET AA.TG_SMPL; KEEP HHRR_HEAD_INDI_DSCM_NO STD_YYYY;RUN;


/* (서울) 0.		서울 전수 + 2019년 */
%MACRO BRT_Y; 
%DO YY=2002 %TO 2019; 
PROC SQL; 
connect to saphana as X1(server=pepper1 port=30015 user=&DB_USER password=!&DB_USER1 readbuff=32767 insertbuff=32767);
CREATE TABLE AA.BFC_&YY. AS
SELECT * 
FROM CONNECTION TO X1
(
	SELECT A.STD_YYYY,
				A.INDI_DSCM_NO,
				A.SEX_TYPE,
				A.BYEAR,
				A.FST_DAY_Y,
				A.STD_DT,
				A.JUNG_NO,
				A.GAIBJA_TYPE,
				A.JUNG_NO_YY,
				A.GAIBJA_TYPE_YY,
				A.HI_MIN_YYYYMM,
				A.HI_MAX_YYYYMM,
				A.HI_CNT_M,
				A.HHRR_HEAD_INDI_DSCM_NO,
				A.HHRR_HEAD_INDI_DSCM_NO_MY,
				A.RVSN_ADDR_CD_MY,
				A.SUM_CALC_CTRB,
				A.SUM_CTRB_ADJ,
				A.CNT_CTRB_M,
				A.EMP_Y,
				A.EMP_ADJ_CMPLT_YN,
				A.CNT_FIRM,
				A.SUM_WRK_M,
				A.INC_TAX_TYPE,
				A.INC_WAGE,
				A.INC_BUS,
				A.INC_INT,
				A.INC_DIVID,
				A.INC_PNSN_NATL,
				A.INC_PNSN_OCCUP,
				A.INC_OTHR,
				A.INC_TOT,
				A.PROP_TXBS_BLDG,
				A.PROP_TXBS_LND,
				A.CALC_CTRB_FD,
				A.PROP_TXBS_HS,
				A.CALC_CTRB_VTILE_FD,
				A.PROP_TXBS_SHIP,
				A.CTRB_ADJ_FD,
				A.PROP_TXBS_TOT,
				A.CTRB_ADJ_VTILE_FD,
				A.CNT_ID_HHHI_FD,
				A.FOREIGNER_Y,
				A.RVSN_ADDR_CD_Y,
				A.CMPR_DSB_GRADE,
				A.MAIN_DSB_TYPE,
				A.INDTP_CD,
				A.FIRM_SCL_ENTER_NOP_ID,
				A.FIRM_CD,
				A.RVSN_ADDR_CD,
				A.RVSN_ADDR_TYPE,
				A.RVSN_FIRM_ADDR_CD,
				A.MCBNF_CLSFC_CD,
				A.MCBNF_PTTN_CD,
				C.FMLY_LINE
	FROM NHISBDA.HHDT_DSES_YY AS A
	INNER JOIN TMP_INDI_&P_N._ALL AS B
		ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
	LEFT JOIN NHISBDA.HHST_FAMILY AS C
		ON B.INDI_DSCM_NO=C.TG_ID AND 
			A.HHRR_HEAD_INDI_DSCM_NO=C.FMLY_ID
	WHERE A.STD_YYYY=%nrbquote('&YY.')
		AND A.INDI_DSCM_NO<>0 
		AND A.INDI_DSCM_NO IS NOT NULL 
		AND A.STD_YYYY >= A.BYEAR
);disconnect from x1;
QUIT;  
%END; 
%MEND BRT_Y; 
%BRT_Y;

/* (전국) 1.		2003년, 2010년, 2019년 1% 가구(서울 포함 전국) 추출 + 가구원 + 가족 
		 1.2	가구원 및 가족 결합한 테이블 구성*/
%MACRO BRT_Y; 
%LET YYS = 2003 2010 2019;
%DO i=1 %to %SYSFUNC(COUNTW(&YYS));
%LET YY = %SCAN(&YYS, &i);
PROC SQL; connect to saphana as X1(server=pepper1 port=30015 user=&DB_USER password=!&DB_USER1 readbuff=32767 insertbuff=32767);
CREATE TABLE AA.BFC_&YY._SMPL_XSECTION AS
SELECT * 
FROM CONNECTION TO X1
(
	SELECT A.STD_YYYY,
				A.INDI_DSCM_NO,
				A.SEX_TYPE,
				A.BYEAR,
				A.FST_DAY_Y,
				A.STD_DT,
				A.JUNG_NO,
				A.GAIBJA_TYPE,
				A.JUNG_NO_YY,
				A.GAIBJA_TYPE_YY,
				A.HI_MIN_YYYYMM,
				A.HI_MAX_YYYYMM,
				A.HI_CNT_M,
				A.HHRR_HEAD_INDI_DSCM_NO,
				A.HHRR_HEAD_INDI_DSCM_NO_MY,
				A.RVSN_ADDR_CD_MY,
				A.SUM_CALC_CTRB,
				A.SUM_CTRB_ADJ,
				A.CNT_CTRB_M,
				A.EMP_Y,
				A.EMP_ADJ_CMPLT_YN,
				A.CNT_FIRM,
				A.SUM_WRK_M,
				A.INC_TAX_TYPE,
				A.INC_WAGE,
				A.INC_BUS,
				A.INC_INT,
				A.INC_DIVID,
				A.INC_PNSN_NATL,
				A.INC_PNSN_OCCUP,
				A.INC_OTHR,
				A.INC_TOT,
				A.PROP_TXBS_BLDG,
				A.PROP_TXBS_LND,
				A.CALC_CTRB_FD,
				A.PROP_TXBS_HS,
				A.CALC_CTRB_VTILE_FD,
				A.PROP_TXBS_SHIP,
				A.CTRB_ADJ_FD,
				A.PROP_TXBS_TOT,
				A.CTRB_ADJ_VTILE_FD,
				A.CNT_ID_HHHI_FD,
				A.FOREIGNER_Y,
				A.RVSN_ADDR_CD_Y,
				A.CMPR_DSB_GRADE,
				A.MAIN_DSB_TYPE,
				A.INDTP_CD,
				A.FIRM_SCL_ENTER_NOP_ID,
				A.FIRM_CD,
				A.RVSN_ADDR_CD,
				A.RVSN_ADDR_TYPE,
				A.RVSN_FIRM_ADDR_CD,
				A.MCBNF_CLSFC_CD,
				A.MCBNF_PTTN_CD,
				C.FMLY_LINE
	FROM NHISBDA.HHDT_DSES_YY AS A
	/* 가구주 INNER JOIN 대신, 가구주의 가구원이 아닌 가족도 포함될 수 있도록 수정 가능할까요?*/
	/* 만약 가능하다면 잘은 모르지만 아래와 같은 조건을 걸 수 있지 않을까 합니다.             */
	/* WHERE (A.HHRR_HEAD_INDI_DSCM_NO=B.HHRR_HEAD_INDI_DSCM_NO 
			OR (B.HHRR_HEAD_INDI_DSCM_NO=C.FMLY_ID 
				AND A.INDI_DSCM_NO=C.TG_ID))
		AND A.STD_YYYY=B.STD_YYYY
		AND B.STD_YYYY=%nrbquote('&YY.')
	*/
	INNER JOIN TMP_INDI_&P_N._SMPL_XSECTION AS B
	ON A.HHRR_HEAD_INDI_DSCM_NO=B.HHRR_HEAD_INDI_DSCM_NO
	AND A.STD_YYYY=B.STD_YYYY
	AND B.STD_YYYY=%nrbquote('&YY.')
	LEFT JOIN NHISBDA.HHST_FAMILY AS C
	ON A.INDI_DSCM_NO=C.TG_ID
	AND B.HHRR_HEAD_INDI_DSCM_NO=C.FMLY_ID
	/* -----------------------------------------------------------------------*/
		WHERE A.STD_YYYY=%nrbquote('&YY.')
			AND A.INDI_DSCM_NO<>0 
			AND A.INDI_DSCM_NO IS NOT NULL 
			AND A.STD_YYYY >= A.BYEAR
);disconnect from x1;
QUIT; 
%END; %MEND BRT_Y; %BRT_Y;


%MACRO BRT_Y; %DO YY=2002 %TO 2019; 
PROC SQL; connect to saphana as X1(server=pepper1 port=30015 user=&DB_USER password=!&DB_USER1 readbuff=32767 insertbuff=32767);
CREATE TABLE AA.BFC_&YY._SMPL_PANEL AS
SELECT * 
FROM CONNECTION TO X1
(
	SELECT A.STD_YYYY,
				A.INDI_DSCM_NO,
				A.SEX_TYPE,
				A.BYEAR,
				A.FST_DAY_Y,
				A.STD_DT,
				A.JUNG_NO,
				A.GAIBJA_TYPE,
				A.JUNG_NO_YY,
				A.GAIBJA_TYPE_YY,
				A.HI_MIN_YYYYMM,
				A.HI_MAX_YYYYMM,
				A.HI_CNT_M,
				A.HHRR_HEAD_INDI_DSCM_NO,
				A.HHRR_HEAD_INDI_DSCM_NO_MY,
				A.RVSN_ADDR_CD_MY,
				A.SUM_CALC_CTRB,
				A.SUM_CTRB_ADJ,
				A.CNT_CTRB_M,
				A.EMP_Y,
				A.EMP_ADJ_CMPLT_YN,
				A.CNT_FIRM,
				A.SUM_WRK_M,
				A.INC_TAX_TYPE,
				A.INC_WAGE,
				A.INC_BUS,
				A.INC_INT,
				A.INC_DIVID,
				A.INC_PNSN_NATL,
				A.INC_PNSN_OCCUP,
				A.INC_OTHR,
				A.INC_TOT,
				A.PROP_TXBS_BLDG,
				A.PROP_TXBS_LND,
				A.CALC_CTRB_FD,
				A.PROP_TXBS_HS,
				A.CALC_CTRB_VTILE_FD,
				A.PROP_TXBS_SHIP,
				A.CTRB_ADJ_FD,
				A.PROP_TXBS_TOT,
				A.CTRB_ADJ_VTILE_FD,
				A.CNT_ID_HHHI_FD,
				A.FOREIGNER_Y,
				A.RVSN_ADDR_CD_Y,
				A.CMPR_DSB_GRADE,
				A.MAIN_DSB_TYPE,
				A.INDTP_CD,
				A.FIRM_SCL_ENTER_NOP_ID,
				A.FIRM_CD,
				A.RVSN_ADDR_CD,
				A.RVSN_ADDR_TYPE,
				A.RVSN_FIRM_ADDR_CD,
				A.MCBNF_CLSFC_CD,
				A.MCBNF_PTTN_CD,
				C.FMLY_LINE
	FROM NHISBDA.HHDT_DSES_YY AS A
	INNER JOIN TMP_INDI_&P_N._SMPL_PANEL AS B
	ON A.HHRR_HEAD_INDI_DSCM_NO=B.HHRR_HEAD_INDI_DSCM_NO /*연도에 상관없이 샘플된 가구주만*/
	LEFT JOIN NHISBDA.HHST_FAMILY AS C
	ON A.INDI_DSCM_NO=C.TG_ID
	AND B.HHRR_HEAD_INDI_DSCM_NO=C.FMLY_ID
		WHERE A.STD_YYYY=%nrbquote('&YY.')
			AND A.INDI_DSCM_NO<>0 
			AND A.INDI_DSCM_NO IS NOT NULL 
			AND A.STD_YYYY >= A.BYEAR
);disconnect from x1;
QUIT;  
%END; %MEND BRT_Y; %BRT_Y;

